### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by doug-leith** [google/federated-compute#1]
build exits with errors:

ERROR: /root/.cache/bazel/_bazel_root/a2d1cfe108fb6ecf8584c66084ab27f5/external/boringssl/BUILD:161:11: Compiling src/crypto/evp/p_x25519.c failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 40 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
cc1: error: command line option '-std=c++17' is valid for C++/ObjC++ but not for C [-Werror]
cc1: all warnings being treated as errors
ERROR: /root/.cache/bazel/_bazel_root/a2d1cfe108fb6ecf8584c66084ab27f5/external/boringssl/BUILD:161:11: Compiling src/crypto/asn1/a_mbstr.c failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 40 arguments skipped)

looks like an easy fix.

**Comment by timonvo** [comment]
Thanks for the report. I believe the error you're seeing is likely due to some behavioral differences between clang (which we use internally) and GCC (which we test less frequently).

Would you be able to provide a bit more info:
- What version of GCC are you using?
- What bazel(isk) command are you running that leads to this error? Are you basically running the steps in https://github.com/google/federated-compute/blob/main/GETTING_STARTED.md#build-and-run-the-federated-program-test, or are you doing anything differently?
- In https://github.com/google/federated-compute/issues/2 you mentioned you commented out the Werror flag. Were you referring to the flag listed in the .bazelrc [here](https://github.com/google/federated-compute/blob/66a21c9068a5ff9fbedf1ccd2cc33b985d55f15b/.bazelrc#L45)? Or did you comment out another line? I ask because the line I linked to is meant to only apply to clang-based builds (I think we purposely turned -Werror off for the default/GCC-based builds since GCC's Werror is a bit too eager.) If that was the line you edited, then are you accidentally passing "--config=clang" by chance?

**Comment by timonvo** [comment]
I believe that commit 449b2f4 should've fixed this issue by now.
